apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-end-to-end-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: complete-end-to-end-pipeline
  template:
    metadata:
      labels:
        app: complete-end-to-end-pipeline
    spec:
      containers:
      - name: complete-end-to-end-pipeline
        image: bilal4178/complete-prodcution-e2e-pipeline
        ports:
          - containerPort: 8080
