apiVersion: v1
kind: Service
metadata:
  name: complete-end-to-end-pipeline
spec:
  selector:
    app: complete-end-to-end-pipeline
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
